language: perl
sudo: false
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
# See https://travis-ci.org/yoheimuta/Linux-GetPidstat/jobs/137011297
# - "5.10"
install:
  - cpanm --notest Minilla Test::CPAN::Meta Test::Pod Test::MinimumVersion::Fast Test::PAUSE::Permissions Test::Spellunker
  - cpanm --quiet --with-develop --installdeps --notest .
script:
  - minil test --all
